### ISSUE TITLE
travis-ci: unable to deploy to the puppet forge

### ISSUE THREAD

**Issue by johanfleury** [puppetlabs/pdk-templates#140]
Due to `dpl-puppet_forge` requiring the very last version of Ruby (wtf, seriously), it is not possible to push to the forge with the default generated travis-ci configuration:

```
ERROR:  Error installing dpl-puppet_forge:
	The last version of puppet (>= 0) to support your Ruby & RubyGems was 5.5.6. Try installing it with `gem install puppet -v 5.5.6` and then running the current command again
	puppet requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
```

```
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- dpl/provider/puppet_forge (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/lib/dpl/provider.rb:94:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/lib/dpl/provider.rb:69:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/lib/dpl/provider.rb:68:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.0/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by DavidS** [comment]
seems like `dpl-puppet_forge` is now working on all ruby versions that we support (https://rubygems.org/gems/dpl-puppet_forge says `>= 2.2`), so I'm closing this issue.
